"""move expires_at field to client model

Revision ID: c7ea6ded3358
Revises: e7b0fb25b8e9
Create Date: 2026-02-06 11:14:43.964330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7ea6ded3358'
down_revision: Union[str, Sequence[str], None] = 'e7b0fb25b8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('peers', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peers', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('clients', 'expires_at')
    # ### end Alembic commands ###
